Update SuspicionSystemClass
Nijelous/CSC8508-2023 pull request #103
Opened 2024-02-13 18:04 UTC by KyriakosNU

2024-02-13 18:47 UTC, Nijelous requested changes
If this is necessary then sure I'll approve this but I think you put this in accidentally.

2024-02-13 18:47 UTC, Nijelous commented on CSC8503/SuspicionSystem/SuspicionSystem.h
> +#include "LocationBasedSuspicion.h"mLocationBasedSuspicionPtr
Why is mLocationBasedSuspicionPtr there?

2024-02-14 00:22 UTC, Nijelous approved these changes

2024-02-14 11:13 UTC, benblack90 approved these changes

2024-02-14 11:13 UTC, benblack90 commented on CSC8503/SuspicionSystem/SuspicionSystem.h
> +	class SuspicionSystemClass
This is going to need a more descriptive name, such as SuspicionSystemData

2024-02-14 14:08 UTC, merged