Inventory buff system/ctp 61 item effects
Nijelous/CSC8508-2023 pull request #109
Opened 2024-02-14 16:00 UTC by KyriakosNU

This PR Includes:
"Fixes" to the system that chooses what random buff/item a pickup is. * (they are random, but without using a pre-defined seed)
Fixes so that the pickups can be added and properly updated in the world
Disguise and sound emitter items, including 
SoundEmitter Object and adding it to the world

2024-02-14 16:17 UTC, Nijelous approved these changes

2024-02-15 10:39 UTC, benblack90 requested changes
Sorry to not approve, but I keep commenting about curly braces, and I'm not sure you see them. Please correct the curly braces in this pull request, and all the classes you've written.

2024-02-15 10:39 UTC, benblack90 commented on CSC8503/InventoryBuffSystem/PlayerBuffs.cpp
> +	{
The curly braces should be on the previous line. I know coding standards like this are annoying, but please adhere to them. It makes our code more consistent.

2024-02-15 11:55 UTC, erendgrmnc approved these changes

2024-02-15 12:29 UTC, benblack90 approved these changes

2024-02-15 12:47 UTC, merged