Integrate FMOD to our project
Nijelous/CSC8508-2023 pull request #146
Opened 2024-02-22 18:33 UTC by fm19121

Integrate FMOD, we can use some thing in the library, but no sound for now.
Also, changed suspension indicator icon texture.
Nothing changed in any functionalities.

2024-02-22 18:58 UTC, Nijelous requested changes
Look good, glad it compiles, but remove all the irrKlang stuff please.

2024-02-22 19:30 UTC, fm19121 commented
All things about irrKlang and irrKlang itself are removed

2024-02-22 19:31 UTC, Nijelous approved these changes

2024-02-23 10:49 UTC, benblack90 approved these changes

2024-02-23 11:08 UTC, merged