Global Suspicion Metre Added
Nijelous/CSC8508-2023 pull request #15
Opened 2024-02-02 15:27 UTC by KyriakosNU

The global suspicion metre required by the suspicion system

2024-02-02 15:45 UTC, benblack90 requested changes
Looks good, mostly! Just some little things I think need changing, and one thing I want to ask the group about.

2024-02-02 15:45 UTC, benblack90 commented on CSC8503/SuspicionSystem/GlobalSuspicionMetre.h
> +        allarmTriggered, flagCaptured
should be 'alarmTriggered'

2024-02-02 15:45 UTC, benblack90 commented on CSC8503/SuspicionSystem/GlobalSuspicionMetre.h
> +    const enum activeGlobalSusCause
Instant vs active is a bit confusing - I think what you mean is 'instant' happens in one instant, and 'active' is over a time period?

Perhaps Single and Continuous or Repeating?

2024-02-02 15:45 UTC, benblack90 commented on CSC8503/SuspicionSystem/GlobalSuspicionMetre.h
> +    bool AddActiveGlobalSusCause(activeGlobalSusCause inCause);
These should all be bool, or all be void. 

I'm in two minds about the bool names - I've seen this pattern before (adding an entity successfully returns true), but it does break our rule about the method name being answerable as 'true' or 'false'. I'm leaning towards it being fine, but I'll put it to the rest of the team.

2024-02-02 15:45 UTC, benblack90 commented on CSC8503/SuspicionSystem/GlobalSuspicionMetre.h
> +        {allarmTriggered,3}, {flagCaptured, 2}
alarm instead of allarm

2024-02-02 15:45 UTC, benblack90 commented on CSC8503/SuspicionSystem/GlobalSuspicionMetre.h
> +    void ChangePlayerGlobalSusMetre(float ammount);
should be amount, not ammount

2024-02-02 15:45 UTC, benblack90 commented on CSC8503/SuspicionSystem/GlobalSuspicionMetre.cpp
> +    //If the foundCause is not already in the mActiveGlobalSusCauseVector vector of that player
comment not needed - I think it's pretty clear as is that you're using an iterator, so reaching .end() means it was not found

2024-02-03 12:40 UTC, erendgrmnc commented on CSC8503/SuspicionSystem/GlobalSuspicionMetre.cpp
> +    auto foundCause = std::find(mActiveGlobalSusCauseVector.begin(), mActiveGlobalSusCauseVector.end(), inCause);
How about using "auto*" for creating a pointer rather than copying the value 🤔

2024-02-05 17:47 UTC, benblack90 approved these changes

2024-02-05 17:47 UTC, benblack90 commented on CSC8503/SuspicionSystem/GlobalSuspicionMetre.cpp
>      mGlobalSusMeter += ammount;
ammount is still misspelled in the function body - you might need to search for it

2024-02-05 17:47 UTC, benblack90 commented on CSC8503/SuspicionSystem/GlobalSuspicionMetre.h
> +        {allarmTriggered,3}, {flagCaptured, 2}
still need to change allarm here :)

2024-02-07 01:54 UTC, Chenziyes commented
Sorry to notice it too late(I struggled with animation until now), I saw Ben approved this request, meaning the code should have been changed. But I still can't see the updated code.

2024-02-08 17:54 UTC, Nijelous approved these changes

2024-02-09 11:34 UTC, merged