feature/add-imgui-to-project
Nijelous/CSC8508-2023 pull request #244
Opened 2024-03-11 23:50 UTC by erendgrmnc

2024-03-12 03:22 UTC, Nijelous requested changes
Before this is pushed we absolutely need it to load singleplayer and multiplayer games, because as is unless I'm missing something there is no way to access the singleplayer game which means pushing this would prove problematic for testing other features

2024-03-12 03:22 UTC, Nijelous commented on CSC8503/MainMenuScene.cpp
> +	ImGui::SetCursorPos(ImVec2(windowSize.x * .01f, windowSize.y * .0`1f));
Might wanna remove the ` from the .01f you got there

2024-03-12 12:12 UTC, erendgrmnc commented
> Before this is pushed we absolutely need it to load singleplayer and multiplayer games, because as is unless I'm missing something there is no way to access the singleplayer game which means pushing this would prove problematic for testing other features

@Nijelous Oh this pr is currently in progress, I added the wrong tag 🤦sry fr that :(

2024-03-13 18:14 UTC, Nijelous approved these changes

2024-03-14 17:15 UTC, fm19121 approved these changes

2024-03-15 18:10 UTC, merged