CTP 38 implement friction
Nijelous/CSC8508-2023 pull request #38
Opened 2024-02-05 18:35 UTC by squiree98

2024-02-05 23:45 UTC, Nijelous requested changes
Overall looks good, but to keep up coding standards if you could update the member variables to meet the standard we're going for in PhysicsObject and PhysicsSystem that would be much appreciated.

2024-02-06 10:20 UTC, benblack90 approved these changes
Just some little nit-picky comments! Mostly fine and swell

2024-02-06 10:20 UTC, benblack90 commented on CSC8503CoreClasses/PhysicsSystem.cpp
> +	contactVelocity = (GetIsCapsule(a) || GetIsCapsule(b) ? contactVelocity = physB->GetLinearVelocity() - physA->GetLinearVelocity() : contactVelocity = CalculateCollisionVelocity(relativeA, relativeB,
This took a little bit for me to parse: I think you don't need the two 'contactVelocity = ' re-statements in a ternary. So it should read:
contactVelocity = (GetIsCapsule(a) || GetIsCapsule(b)) ? physB->GetLinearVelocity() - physA->GetLinearVelocity : 
                              CalculateCollisionVelocity(relativeA, relativeB, physA, physB);

Which may well still be a little confusing! If-else might be clearer here, but that's up to you.

2024-02-06 10:20 UTC, benblack90 commented on CSC8503CoreClasses/PhysicsSystem.cpp
> +	if (totalMass == 0)
Is there any way mass could (presumably incorrectly) be less than 0? Do we need to check for it?

2024-02-06 10:20 UTC, benblack90 commented on CSC8503CoreClasses/PhysicsSystem.cpp
> +	transformA.SetPosition(transformA.GetPosition() - (p.normal * p.penetration * (a.GetPhysicsObject()->GetInverseMass() / totalMass)));
CheckFrictionShouldBeApplied checks for 0, implying 0 is a possible totalMass. If that's the case, we could be dividing by zero!
If 0 isn't a possibility, maybe we should assert that. If it is, we need to protect this function from the possibility.

2024-02-06 12:02 UTC, Nijelous approved these changes

2024-02-06 12:02 UTC, merged