Base of location Based Suspicion
Nijelous/CSC8508-2023 pull request #45
Opened 2024-02-07 10:57 UTC by KyriakosNU

2024-02-07 12:36 UTC, Nijelous requested changes
A couple quick changes but the code looks solid, and I assume it works.

2024-02-07 12:36 UTC, Nijelous commented on CSC8503/SuspicionSystem/SuspicionMetre.h
> +		SusBreakpoint getSusBreakpoint(float inSusMetre);
Capitals for Functions

2024-02-07 12:36 UTC, Nijelous commented on CSC8503/SuspicionSystem/SuspicionMetre.h
> +		std::map<float, SusBreakpoint> SusBreakpointMap = { { 66 , high} ,
mSusBreakpointMap

2024-02-07 15:29 UTC, Nijelous approved these changes

2024-02-08 14:39 UTC, fm19121 approved these changes
curly brackets

2024-02-09 11:34 UTC, merged