Player Inventory Base
Nijelous/CSC8508-2023 pull request #47
Opened 2024-02-07 11:29 UTC by KyriakosNU

2024-02-07 12:50 UTC, Nijelous requested changes
Again, overall code looks good, please make recommended changes

2024-02-07 12:50 UTC, Nijelous commented on CSC8503/InventoryBuffSystem/PlayerInventory.h
> +		};
mItemsInRandomPool
mItemInitDurationMap

2024-02-07 12:50 UTC, Nijelous commented on CSC8503/InventoryBuffSystem/PlayerInventory.cpp
> +		for (int playerNo = 0; playerNo < 4; playerNo++)
Probably should remove the "magic number" of 4, make it a constexpr of PLAYER_MAX

2024-02-07 12:50 UTC, Nijelous commented on CSC8503/InventoryBuffSystem/PlayerInventory.cpp
> +			for (int invSlot = 0; invSlot < 2; invSlot++)
Same for this, you've even used it further down as MAX_INVENTORY_SLOTS you just need to add it here

2024-02-07 12:50 UTC, Nijelous commented on CSC8503/InventoryBuffSystem/PlayerInventory.cpp
> +		for (int invSlot = 0; invSlot < 2; invSlot++)
And here

2024-02-07 15:43 UTC, Nijelous requested changes

2024-02-07 15:43 UTC, Nijelous commented on CSC8503/InventoryBuffSystem/PlayerInventory.h
>  	const int MAX_INVENTORY_SLOTS = 4;
Needs to be 2 slots, not 4

2024-02-07 18:42 UTC, Nijelous approved these changes

2024-02-08 14:23 UTC, fm19121 commented on CSC8503/InventoryBuffSystem/PlayerInventory.cpp
> +	{
Looks good, but in our code stander. The curly bracket should be on the same line with the function, like:
void PlayerInventory::Init(){
         .......
         ........
}

2024-02-08 14:31 UTC, fm19121 approved these changes

2024-02-08 17:40 UTC, merged