Suspicion system local and global
Nijelous/CSC8508-2023 pull request #50
Opened 2024-02-07 14:26 UTC by KyriakosNU

2024-02-07 18:46 UTC, Nijelous requested changes
Make sure to update the variables, again looking over the code it looks solid.

2024-02-07 18:46 UTC, Nijelous commented on CSC8503/SuspicionSystem/SuspicionMetre.h
> +	SusBreakpoint getSusBreakpoint(float inSusMetre);
GetSusBreakpoint

2024-02-07 18:46 UTC, Nijelous commented on CSC8503/SuspicionSystem/SuspicionMetre.h
> +	std::map<float, SusBreakpoint> SusBreakpointMap = { { 66 , high} ,
mSusBreakpointMap

2024-02-08 02:11 UTC, Nijelous approved these changes

2024-02-08 14:10 UTC, ollieiscool approved these changes

2024-02-08 14:16 UTC, merged